//
// Created by alice on 17/02/2020.
//

#ifndef IMPLIMENTINGGAMEAUDIOPROJECT_RAYLIB_INPUTEVENT_H
#define IMPLIMENTINGGAMEAUDIOPROJECT_RAYLIB_INPUTEVENT_H


class InputEvent: public Event
{




};
#endif //IMPLIMENTINGGAMEAUDIOPROJECT_RAYLIB_INPUTEVENT_H
