//
// Created by alice on 14/02/2020.
//

#ifndef IMPLIMENTINGGAMEAUDIOPROJECT_RAYLIB_GLOBALS_H
#define IMPLIMENTINGGAMEAUDIOPROJECT_RAYLIB_GLOBALS_H
namespace GlobalVARS{
   const int RENDERW = 640;
   const int RENDERH = 480;


};
#endif //IMPLIMENTINGGAMEAUDIOPROJECT_RAYLIB_GLOBALS_H
